name: Check Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check:
    uses: reqstool/.github/.github/workflows/check-semantic-pr.yml@33502e31f66fb7e982f48f50e3c6c29b0410a017 # main 2026-03-07
